language: go

go:
  - 1.3.3
  - 1.4.1

env:
  - GOARCH=amd64
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)

notifications:
  email:
    recipients:
      - kevin.bowrin@carleton.ca
    on_success: change
    on_failure: always
